import { NextResponse } from 'next/server';
import { createOrConnectWorkspace, writeFile, executeCommand, createDirectory, getWorkspaceDir } from '@/lib/sandbox';
import { spawn } from 'child_process';
import path from 'path';

const STARTER_FILES = {
  '/tmp/app/package.json': `{
  "name": "velvet-next-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev -H 0.0.0.0 -p 3001",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "next": "^14.2.3",
    "lucide-react": "^0.395.0",
    "clsx": "^2.1.1",
    "tailwind-merge": "^2.3.0"
  },
  "devDependencies": {
    "typescript": "^5.4.5",
    "@types/node": "^20.14.2",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "postcss": "^8.4.38",
    "tailwindcss": "^3.4.4",
    "autoprefixer": "^10.4.19"
  }
}`,
  '/tmp/app/tailwind.config.ts': `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;`,
  '/tmp/app/postcss.config.js': `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};`,
  '/tmp/app/tsconfig.json': `{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`,
  '/tmp/app/app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #050505;
  --foreground: #ffffff;
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: Arial, Helvetica, sans-serif;
}`,
  '/tmp/app/app/layout.tsx': `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Velvet App",
  description: "Generated by Velvet AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}`,
  '/tmp/app/app/page.tsx': `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Sandbox Ready</h1>
      <p className="mt-4 text-slate-400">Waiting for Velvet AI to generate your application...</p>
    </main>
  );
}`
};

export const maxDuration = 60;

// To store running dev server processes
const runningServers: Record<string, any> = {};

export async function POST(req: Request) {
  try {
    const { sandboxId } = await req.json().catch(() => ({}));

    // If sandboxId is specified, connect. If not, create a new one.
    const isNew = !sandboxId;
    const workspace = await createOrConnectWorkspace(sandboxId);

    if (isNew) {
      console.log('Initializing starter files in workspace:', workspace.id);

      // Create directory
      await createDirectory(workspace.id, '/tmp/app/src');

      // Write all starter files in parallel
      console.log('Writing', Object.keys(STARTER_FILES).length, 'starter files...');
      await Promise.all(
        Object.entries(STARTER_FILES).map(([filePath, content]) =>
          writeFile(workspace.id, filePath, content)
        )
      );
      console.log('All starter files written successfully.');

      // Run npm install synchronously
      console.log('Running npm install...');
      await executeCommand(workspace.id, 'npm install', '/tmp/app');

      // Start npm run dev in the background
      console.log('Running npm run dev in background...');
      const appDir = path.join(getWorkspaceDir(workspace.id), 'app'); // Because normalize path strips /tmp/app or handles it. Actually, wait.
      // The writeFile handles '/tmp/app/xxx' correctly by making it relative to workspace root.
      // So the cwd for npm should just be the workspace root if it wrote everything to root, OR if it created a literal /tmp/app folder inside workspace root.
      // Looking at sandbox.ts resolveSafePath, it strips '/tmp/app' completely. 
      // So the project root is the workspace root itself.
      
      const cwd = getWorkspaceDir(workspace.id);
      
      // Stop existing server if any
      if (runningServers[workspace.id]) {
        runningServers[workspace.id].kill();
      }

      // Spawn next dev process
      const devProcess = spawn('npm', ['run', 'dev'], {
        cwd: cwd,
        shell: true,
        detached: true // Let it run independently
      });

      devProcess.stdout.on('data', (data) => console.log(`[DevServer ${workspace.id}]: ${data}`));
      devProcess.stderr.on('data', (data) => console.error(`[DevServer Error ${workspace.id}]: ${data}`));
      
      runningServers[workspace.id] = devProcess;

      // Give Next.js 3 seconds to boot up and bind to port 3001
      await new Promise(resolve => setTimeout(resolve, 3000));
    }

    // Local preview URL runs on 3001
    const previewUrl = `http://localhost:3001`;

    return NextResponse.json({
      success: true,
      sandboxId: workspace.id,
      previewUrl,
    });
  } catch (error: any) {
    console.error('Error in sandbox route:', error);
    return NextResponse.json(
      { success: false, error: error.message || 'Failed to handle workspace lifecycle' },
      { status: 500 }
    );
  }
}
